version: 0.2
env:
  git-credential-helper: yes
  variables:
    PATTERN_REPO: "CXOS-June-Demo"
    DOC_REPO: "CXOS-Test-Documentation"
phases:
  install:
    on-failure: ABORT
    commands:
      - echo -n 'Commit Tag = '
      - aws ssm get-parameter --name  GITACCESS_TOKEN | grep Value 
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - pwd
      - cat README.md
      - cat buildspec.yml
      - chmod +x find-changes.sh
      - ./find-changes.sh
artifacts:
  files:
    - './**/*'
  name: mkdocsSite
  base-directory: CXOSDocs/site
