version: 0.2
env:
  git-credential-helper: yes
  variables:
    PATTERN_REPO: "CXOS-June-Demo"
    DOC_REPO: "CXOS-Test-Documentation"
phases:
  install:
    on-failure: ABORT
    commands:
      - echo 'test codebuild'
      - env  
      
      - apt-get update
      - apt-get -y upgrade
      - apt-get install -y python3 python3-pip zip
      - pip install mkdocs
      - cd CXOSDocs
      - python3 -m mkdocs build
artifacts:
  files:
    - './**/*'
  name: mkdocsSite
  base-directory: CXOSDocs/site
